<img align="right" src="https://ds-cs-images.s3.ap-northeast-2.amazonaws.com/Codestates_Fulllogo_Color.png" width=100>

## *AIB / SECTION 2 / SPRINT 2 / NOTE 2*

# üìù Assignment
---

# ÎûúÎç§Ìè¨Î†àÏä§Ìä∏(Random Forests)

### 1) Ï∫êÍ∏Ä ÎåÄÌöåÎ•º Ïù¥Ïñ¥ÏÑú ÏßÑÌñâÌï©ÎãàÎã§. EDA, Îç∞Ïù¥ÌÑ∞ Ï†ÑÏ≤òÎ¶¨ Î∂ÄÎ∂ÑÏùÑ ÏóÖÎç∞Ïù¥Ìä∏ ÌïòÏÑ∏Ïöî.
- EDAÎäî Ìï≠ÏÉÅ ÏôÑÎ≤ΩÌï† Ïàò ÏóÜÏßÄÏöî Ìïú Ï£ºÍ∞Ñ Í≥ÑÏÜç Í∞ôÏùÄ Îç∞Ïù¥ÌÑ∞Î°ú Í≥ºÏ†úÎ•º ÏßÑÌñâÌïòÎØÄÎ°ú Î∂ÄÏ°±Ìïú Î∂ÄÎ∂ÑÏùÑ Ï∂îÍ∞ÄÌïòÍ±∞ÎÇò ÎÖºÌïòÏÑ∏Ïöî.
- (ÏßÄÍ∏àÏùÄ feature engineeringÏóê ÎÑàÎ¨¥ ÏãúÍ∞ÑÏùÑ Îì§Ïù¥ÏßÄ ÎßàÏÑ∏Ïöî!)
- Ordinal EncodingÏùÑ Ï†ÅÏö©Ìï¥ Î≥¥ÏÑ∏Ïöî.
- **(Urclass Quiz) Îã§Ïùå ÌäπÏÑ±Îì§ Ï§ëÏóê ÏàúÏÑúÎ•º Í≥†Î†§Ìïú Ordinal EncodingÏù¥ ÌïÑÏöîÌï¥ Î≥¥Ïù¥Îäî ÌäπÏÑ±ÏùÑ Í≥†Î•¥ÏÑ∏Ïöî.**
    1. opinion_h1n1_vacc_effective
    2. state
    3. marital
    4. employment_occupation

In [2]:
import pandas as pd
from google.colab import files

file = files.upload()

Saving submission.csv to submission.csv
Saving test.csv to test.csv
Saving train.csv to train.csv
Saving train_labels.csv to train_labels.csv

In [93]:
submission = pd.read_csv('submission.csv')
test = pd.read_csv('test.csv')
train = pd.read_csv('train.csv')
train_labels = pd.read_csv('train_labels.csv')

In [94]:
from sklearn.model_selection import train_test_split

target = 'vacc_h1n1_f'
train = pd.merge(train, train_labels[target], left_index=True, right_index=True)

train, val = train_test_split(train, train_size=0.80, test_size=0.20, stratify=train[target], random_state=2)

In [95]:
def feature_engineering(df):
    behaviorals = [col for col in df.columns if 'behavior' in col]
    df['behavior'] = df[behaviorals].sum(axis = 1)
    df.drop(columns = behaviorals, inplace = True)

    dels = [col for col in df.columns if 'seas' in col or 'employment' in col]
    df.drop(columns = dels, inplace = True)

    return df

train = feature_engineering(train)
val = feature_engineering(val)
test = feature_engineering(test)

X_train = train.drop(target, axis=1)
y_train = train[target]
X_val = val.drop(target, axis=1)
y_val = val[target]

In [100]:
from category_encoders import OrdinalEncoder, OneHotEncoder

columns = [col for col in X_train.columns if 'opinion' in col]
encoder = OrdinalEncoder()
X_train = encoder.fit_transform(X_train)
X_test = encoder.transform(test)
X_val = encoder.transform(X_val)

### 2) ÎûúÎç§Ìè¨Î†àÏä§Ìä∏ Î™®Îç∏ÏùÑ Ï†ÅÏö©Ìïú ÌõÑÏùò Í≤∞Í≥ºÎ•º Ï∫êÍ∏ÄÏóê Ï†úÏ∂úÌïòÏÑ∏Ïöî.
- ÎûúÎç§Ìè¨Î†àÏä§Ìä∏Î•º Ï†ÅÏö©ÌïòÍ≥† ÏÑ±Îä•Ïù¥ Ïò§ÌûàÎ†§ Îñ®Ïñ¥Ï°åÏùÑ ÏàòÎèÑ ÏûàÏäµÎãàÎã§! ÎßåÏïΩ Í∑∏Î†áÎã§Î©¥ Ïù¥Ïú†Î•º Î≥∏Ïù∏ ÎÖºÎ¶¨Î°ú Î∂ÑÏÑùÌï¥ Î≥¥ÏÑ∏Ïöî.
- **(Urclass Quiz) Ï∫êÍ∏Ä LeaderboardÏùò Î≥∏Ïù∏ ScoreÎ•º Ï†úÏ∂úÌïòÏÑ∏Ïöî.**

In [101]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer

pipe = make_pipeline(
    OneHotEncoder(),
    StandardScaler(),
    SimpleImputer(),
    RandomForestClassifier(random_state=10, n_jobs=-1, oob_score=True)
)

pipe.fit(X_train, y_train)
pipe.score(X_val, y_val)
X_train

Warning: No categorical columns found. Calling 'transform' will only return input data.

,h1n1_concern,h1n1_knowledge,doctor_recc_h1n1,chronic_med_condition,child_under_6_months,health_insurance,health_worker,opinion_h1n1_vacc_effective,opinion_h1n1_risk,opinion_h1n1_sick_from_vacc,...,marital,rent_own_r,census_region,census_msa,n_adult_r,household_children,n_people_r,hhs_region,state,behavior
20365,1.0,1.0,0.0,1.0,0.0,NaN,0.0,1,1,1,...,2.0,1.0,1,1,4.0,0.0,4.0,2,1,0.0
29138,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1,2,2,...,2.0,2.0,2,2,2.0,2.0,4.0,7,2,5.0
36128,2.0,2.0,0.0,1.0,0.0,1.0,0.0,2,3,3,...,2.0,1.0,4,1,1.0,0.0,1.0,10,3,4.0
39793,2.0,1.0,0.0,0.0,0.0,1.0,0.0,3,1,2,...,1.0,1.0,2,3,2.0,0.0,2.0,7,2,3.0
32973,0.0,1.0,0.0,0.0,0.0,NaN,0.0,4,1,1,...,1.0,1.0,2,2,2.0,3.0,5.0,7,2,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8747,NaN,NaN,0.0,0.0,NaN,1.0,NaN,6,4,6,...,NaN,1.0,2,1,4.0,1.0,5.0,5,22,0.0
4412,3.0,2.0,1.0,0.0,0.0,NaN,0.0,2,2,5,...,1.0,1.0,2,1,2.0,0.0,2.0,5,30,6.0
19064,NaN,NaN,0.0,0.0,NaN,NaN,NaN,6,4,6,...,NaN,1.0,3,2,2.0,1.0,3.0,4,5,0.0
40906,NaN,NaN,0.0,0.0,NaN,1.0,NaN,6,4,6,...,NaN,1.0,4,2,3.0,1.0,4.0,8,21,0.0
30904,2.0,1.0,0.0,1.0,0.0,1.0,0.0,5,1,4,...,2.0,1.0,3,1,2.0,0.0,2.0,4,18,3.0

In [102]:
X_test

,h1n1_concern,h1n1_knowledge,doctor_recc_h1n1,chronic_med_condition,child_under_6_months,health_insurance,health_worker,opinion_h1n1_vacc_effective,opinion_h1n1_risk,opinion_h1n1_sick_from_vacc,...,marital,rent_own_r,census_region,census_msa,n_adult_r,household_children,n_people_r,hhs_region,state,behavior
0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,Not At All Effective,Very Low,Not At All Worried,...,2.0,1.0,2,1,2.0,0.0,2.0,7,29,0.0
1,3.0,0.0,0.0,NaN,NaN,NaN,NaN,Dont Know,Dont Know,Dont Know,...,NaN,NaN,3,3,1.0,0.0,1.0,6,17,3.0
2,1.0,1.0,0.0,0.0,0.0,NaN,0.0,Very Effective,Very Low,Not Very Worried,...,2.0,1.0,1,2,1.0,0.0,1.0,1,41,3.0
3,2.0,2.0,0.0,0.0,0.0,NaN,0.0,Very Effective,Somewhat High,Not Very Worried,...,1.0,1.0,4,1,2.0,0.0,2.0,9,35,0.0
4,2.0,1.0,0.0,0.0,0.0,NaN,0.0,Somewhat Effective,Somewhat Low,Not Very Worried,...,2.0,1.0,1,2,1.0,0.0,1.0,1,41,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28099,0.0,1.0,0.0,1.0,0.0,1.0,0.0,Somewhat Effective,Somewhat Low,Not Very Worried,...,2.0,2.0,2,3,3.0,1.0,4.0,7,36,6.0
28100,3.0,2.0,0.0,1.0,0.0,1.0,0.0,Somewhat Effective,Somewhat Low,Somewhat Worried,...,1.0,1.0,3,1,2.0,0.0,2.0,4,18,4.0
28101,1.0,1.0,0.0,0.0,0.0,NaN,0.0,Very Effective,Very Low,Not Very Worried,...,1.0,1.0,4,1,3.0,0.0,3.0,9,35,3.0
28102,2.0,1.0,0.0,1.0,0.0,1.0,0.0,Somewhat Effective,Very High,Not At All Worried,...,1.0,99.0,2,3,2.0,2.0,4.0,7,50,3.0
28103,2.0,1.0,1.0,0.0,0.0,NaN,0.0,Somewhat Effective,Dont Know,Not Very Worried,...,1.0,1.0,3,2,2.0,0.0,2.0,4,18,1.0

In [103]:
X_val

,h1n1_concern,h1n1_knowledge,doctor_recc_h1n1,chronic_med_condition,child_under_6_months,health_insurance,health_worker,opinion_h1n1_vacc_effective,opinion_h1n1_risk,opinion_h1n1_sick_from_vacc,...,marital,rent_own_r,census_region,census_msa,n_adult_r,household_children,n_people_r,hhs_region,state,behavior
18885,NaN,NaN,0.0,1.0,NaN,1.0,NaN,6,4,6,...,NaN,1.0,3,1,2.0,2.0,4.0,6,46,0.0
8587,1.0,2.0,0.0,0.0,0.0,NaN,1.0,5,1,1,...,1.0,1.0,2,2,2.0,0.0,2.0,7,50,3.0
17917,NaN,NaN,0.0,1.0,NaN,0.0,NaN,6,4,6,...,NaN,1.0,4,1,3.0,1.0,4.0,9,9,0.0
27985,3.0,1.0,1.0,1.0,0.0,1.0,0.0,3,2,4,...,2.0,2.0,3,1,2.0,0.0,2.0,4,13,6.0
917,2.0,0.0,0.0,1.0,0.0,NaN,0.0,5,3,1,...,1.0,1.0,2,1,2.0,0.0,2.0,5,45,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25383,3.0,1.0,1.0,1.0,0.0,1.0,0.0,3,2,5,...,1.0,1.0,3,1,2.0,0.0,2.0,3,14,5.0
37833,2.0,1.0,0.0,0.0,0.0,1.0,0.0,3,3,2,...,NaN,1.0,4,3,2.0,0.0,2.0,8,25,2.0
6921,2.0,2.0,0.0,0.0,0.0,NaN,0.0,3,1,1,...,2.0,2.0,3,1,2.0,0.0,2.0,4,11,3.0
2706,1.0,1.0,0.0,0.0,1.0,1.0,0.0,2,3,2,...,1.0,1.0,4,3,2.0,0.0,2.0,9,9,3.0
17267,3.0,1.0,0.0,0.0,0.0,1.0,0.0,3,2,2,...,1.0,1.0,2,2,2.0,0.0,2.0,7,29,5.0

In [89]:
pred = pipe.predict(test)

ValueError: ignored

## üî• ÎèÑÏ†ÑÍ≥ºÏ†ú(Github - Discussion)

### 3) ÏàòÏóÖÏóê ÏÇ¨Ïö©ÌïòÏßÄ ÏïäÏùÄ Îã§Î•∏ Ï¢ÖÎ•òÏùò [category_encoders](http://contrib.scikit-learn.org/category_encoders/)ÏùÑ 2Í∞ú Ïù¥ÏÉÅ ÏÇ¨Ïö©Ìï¥ Í≤∞Í≥ºÎ•º Í≥µÏú†Ìï¥ Î≥¥ÏãúÍ≥†, Îã§Ïùå ÏßàÎ¨∏Ïóê ÎåÄÌï¥ ÏÑúÎ°ú ÎÖºÏùòÌï¥ Î≥¥ÏÑ∏Ïöî. 

- ÏÇ¨Ïö©ÌïòÏã† encoderÎäî Í∞ÅÍ∞Å Ïñ¥Îñ§ Ïû•Îã®Ï†êÏùÑ Í∞ñÍ≥† ÏûàÏúºÎ©∞, Ïñ¥Îñ§ ÏÉÅÌô©ÏóêÏÑú ÏÇ¨Ïö©ÌïòÎ©¥ Ï¢ãÏùÑÍπåÏöî? 

### 4) Ïôú Ìä∏Î¶¨Î™®Îç∏ÏóêÏÑúÎäî ordinal encodingÏùÑ Ï£ºÎ°ú ÏÇ¨Ïö©ÌïòÎ©∞ (one-hot encodingÎåÄÏã†), Î≤îÏ£ºÌòï ÏûêÎ£åÎ•º ordinal encodingÏúºÎ°ú ÏÇ¨Ïö©Ìï¥ÎèÑ ÎêòÎäî Ïù¥Ïú†Îäî Î¨¥ÏóáÏù¥ÎùºÍ≥† ÏÉùÍ∞ÅÌïòÏãúÎäîÏßÄ ÎÖºÏùòÌï¥ Î≥¥ÏÑ∏Ïöî

## Ï∞∏Í≥†ÏûêÎ£å

- [Random Forests for Complete Beginners](https://victorzhou.com/blog/intro-to-random-forests/)